name: Deploy
  push:
    branches:
      - master
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello, deploying...'

deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout nad clone repo
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}